version: '3.7'

services:
  db:
    image: 
      postgres:14.6
    env_file:
      - ../.env/.db.env
    ports:
      - '5432:5432'
    volumes: 
      - db-data:/var/lib/postgresql/data
    networks:
      - db

volumes:
  db-data: 

networks:
  db:
